#### Import Libs

In [289]:
import os
import re

####  File Utils

In [290]:
def read_file(folder, filename):
    filepath = os.path.join(folder, filename)
    file = open(filepath, 'r')
    page = file.read()
    return page

#### Page Rank

In [352]:
def open_pages(folder):
    filenames = os.listdir(folder)
    page_names = list(map(lambda filename: filename.split('.')[0], filenames))
    pages = []
    for filename in filenames:        
        page = read_file(folder, filename)
        pages.append(page)
    return (pages, page_names)

def page_rank_row(page, page_names, debug):
    # n pages
    n = 6
    
    # search links in the page
    regex_links = "<a href=\"http://(.*?).html"
    matchs = re.findall(regex_links, page)
    
    # probability 
    p = 1/n if len(matchs) == 0 else 1/len(matchs)
    
    # if pagename exist in the page
    ### that position in the array will be a number > 0
    # else
    ### that position in the array will be a number 0
    row = []
    
    if len(matchs) == 0:
        row = [1/n, 1/n, 1/n, 1/n, 1/n, 1/n]
    else:
        for page_name in pages_names:
            row.append(p if page_name in matchs else 0)

    if debug:
        print("=== page ===")
        print("pagenames: {}".format(pages_names))
        print("matchs: {}".format(matchs))
        print("page rank: {}".format(list(map(lambda p: "{:.2f}".format(p), row))))
    
    return row

def page_rank(pages, page_names, debug=False):
    matrix = np.zeros(shape=(len(page_names), len(page_names)))
    for index, page in enumerate(pages):
        row = page_rank_row(page, page_names, debug)
        matrix[index] = row
    return matrix

#### Run

In [353]:
folder = 'paginas'
pages, page_names = open_pages(folder)
matrix = page_rank(pages, page_names, False)

print(matrix)

[[0.         0.         1.         0.         0.         0.        ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.         0.         0.         0.         0.33333333 0.33333333]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.25       0.25       0.         0.25       0.        ]]
