#### Import Libs

In [1]:
import os
import re
import numpy as np

<hr>

1)

####  File Utils

In [2]:
def read_file(folder, filename):
    filepath = os.path.join(folder, filename)
    file = open(filepath, 'r')
    page = file.read()
    return page

In [3]:
link_regex = '<a href=\"http://(.*?).html'

#### Page Rank

In [4]:
def open_pages(folder):
    filenames = os.listdir(folder)
    page_names = list(map(lambda filename: filename.split('.')[0], filenames))
    pages = []
    for filename in filenames:        
        page = read_file(folder, filename)
        pages.append(page)
    return (pages, page_names)

def markov_row(page, page_names):
    # n pages
    n = len(page_names)
    
    # search links in the page
    matchs = re.findall(link_regex, page)
    
    # build adjacency
    row = []
    if len(matchs) == 0:
        row = [1/n, 1/n, 1/n, 1/n, 1/n, 1/n]
    else:
        for page_name in page_names:
            n_matchs = 0
            for match in matchs:
                if page_name == match:
                    n_matchs += 1
            row.append(n_matchs / len(matchs))
    
    return row

def markov_matrix(pages, page_names):
    matrix = np.zeros(shape=(len(page_names), len(page_names)))
    for index, page in enumerate(pages):
        row = markov_row(page, page_names)
        matrix[index] = row
    return matrix

def distribucion_estacionaria(A):
    A = [1,0,0,0,0,0]
    for i in range(1000):
        A = np.dot(A,matrix)
    return A

#### Run

In [5]:
folder = 'paginas'
pages, page_names = open_pages(folder)
matrix = markov_matrix(pages, page_names)

print("Markov Matrix\n")
print(matrix)
print("\n")

page_rank = distribucion_estacionaria(matrix)
print("Page Rank\n")
for i in range(len(page_names)):
    print(page_names[i][:13],"\t",page_rank[i])

Markov Matrix

[[0.         0.5        0.         0.         0.         0.5       ]
 [0.5        0.         0.25       0.         0.25       0.        ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.         0.         1.         0.         0.         0.        ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.66666667 0.33333333 0.         0.         0.         0.        ]]


Page Rank

angelinajolie 	 0.28571428571428525
bradpitt 	 0.24489795918367308
martinscorces 	 0.14285714285714263
robertdeniro 	 0.04081632653061218
jenniferanist 	 0.10204081632653045
jonvoight 	 0.1836734693877548
[0.28571429 0.24489796 0.14285714 0.04081633 0.10204082 0.18367347]


<hr>

3)

<b>Web Service</b>. El cual consulta una <b>Base de Datos</b>.

Dos opciones: <br>
Utilizar dos bases de datos => <b>M/M/2</b> (dos canales de atencion) <br>
Utilizar una base de datos => <b>M/M/1</b> (un canal de atencion) <br>