#### Import Libs

In [582]:
import os
import re
import numpy as np

####  File Utils

In [290]:
def read_file(folder, filename):
    filepath = os.path.join(folder, filename)
    file = open(filepath, 'r')
    page = file.read()
    return page

In [400]:
link_regex = '<a href=\"http://(.*?).html'

#### Page Rank

In [578]:
def open_pages(folder):
    filenames = os.listdir(folder)
    page_names = list(map(lambda filename: filename.split('.')[0], filenames))
    pages = []
    for filename in filenames:        
        page = read_file(folder, filename)
        pages.append(page)
    return (pages, page_names)

def page_rank_row(page, page_names):
    # n pages
    n = len(page_names)
    
    # search links in the page
    matchs = re.findall(link_regex, page)
    
    # build adjacency
    row = []
    if len(matchs) == 0:
        row = [1/n, 1/n, 1/n, 1/n, 1/n, 1/n]
    else:
        for page_name in pages_names:
            n_matchs = 0
            for match in matchs:
                if page_name == match:
                    n_matchs += 1
            row.append(n_matchs / len(matchs))
    
    return row

def page_rank(pages, page_names):
    matrix = np.zeros(shape=(len(page_names), len(page_names)))
    for index, page in enumerate(pages):
        row = page_rank_row(page, page_names)
        matrix[index] = row
    return matrix

def distribucion_estacionaria(A):
    A = [1,0,0,0,0,0]
    for i in range(1000):
        A = np.dot(A,matrix)
    return A

#### Run

In [580]:
folder = 'paginas'
pages, page_names = open_pages(folder)
matrix = page_rank(pages, page_names)
print(matrix)
page_rank = distribucion_estacionaria(matrix)
print(page_rank)

[[0.         0.         1.         0.         0.         0.        ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.         0.         0.         0.         0.66666667 0.33333333]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.25       0.25       0.         0.5        0.        ]]
[0.04081633 0.10204082 0.14285714 0.18367347 0.28571429 0.24489796]
